- include: packages.yml
  tags: packages

- include: ntp.yml
  tags: ntp

- include: locale.yml
  tags: locale

- include: host.yml
  when: "hostname is defined"
  tags: host

- include: motd.yml
  tags: motd

